### ISSUE TITLE
@interact(dP=(0, 4, 0.1)) isn't working

### ISSUE THREAD

**Issue by Niemand112233** [Zabamund/transform2020-getting-started-python#1]
Hi,

I have some problems executing your (very interesting!) tutorial. 
First, an information about using jupyter-notebook instead of the newer jupyter-lab would be good, because the ipywidgets doesn't work with jupyter-lab.

Nevertheless, when I use this code:
`@interact(dP=(0, 4, 0.1))
def make_plot(dP):
    
    # We have to compute Q every time the widget changes...
    Q = flow_rate(k, A, mu, L, dP*1e6) * 3600
    
    # ...and then make the plot again.
    fig, ax = plt.subplots(figsize=(16,6))
    ax.plot(L, Q)
    ax.grid()
    ax.set_title('Flow rate [m3/hr] versus plug length [m]', fontsize=16)
    ax.set_ylabel('Flow rate [m3/hr]', fontsize=14)
    ax.set_xlabel('Plug length [m]', fontsize=14)
    ax.text(0.83, 0.088, f"dP: {dP} MPa", size=20)
    ax.set_ylim(0, 0.1)
    plt.show()
    
    return`

I get a graph and a slider. But the slider doesn't do anything. I can see at the top of jupyer notebook that the kernel is doing something, but the graph doesn't change to the new values. It remains stuck at dP: 2.0 MPa.
Do you have any idea how to solve this?

I created a new notebook with this content:
```
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact

def flow_rate(k, A, mu, L, dP):
    """
    Compute flow rate using Darcy's law
    
    args:
        k: permeability [m2]
        A: area [m2]
        mu: viscosity [Pa.s]
        L: sample_length [m]
        dP pressure differntial [Pa]
    returns:
        Q: flow rate [m3/s]
        """
    Q = ((k * A) / (mu * L)) * dP
    return Q

k = 4.9346165e-13 # ~500 mD
A = 2.03e-3       # 1 inch diameter plug
mu = 8.9e-4       # ~dynamic viscosity of water at about 25°C
L = np.arange(0.05, 1, 0.005) # 2 inch plug
dP = 689476       # ~100 psi

Q = flow_rate(k, A, mu, L, dP) * 3600

@interact(dP=(0, 4, 0.1))
def make_plot(dP):
    
    # We have to compute Q every time the widget changes...
    Q = flow_rate(k, A, mu, L, dP*1e6) * 3600
    
    # ...and then make the plot again.
    fig, ax = plt.subplots(figsize=(16,6))
    ax.plot(L, Q)
    ax.grid()
    ax.set_title('Flow rate [m3/hr] versus plug length [m]', fontsize=16)
    ax.set_ylabel('Flow rate [m3/hr]', fontsize=14)
    ax.set_xlabel('Plug length [m]', fontsize=14)
    ax.text(0.83, 0.088, f"dP: {dP} MPa", size=20)
    ax.set_ylim(0, 0.1)
    plt.show()
    
    return
```

When I run your prefilled file then it will work. Where's the error?

**Comment by Zabamund** [comment]
Hello, 

thanks for checking out this old repo, let me try to answer as best I can:
- why Jupyter Notebook instead of Jupyter Lab: well simply as I used the notebooks more when I wrote that tutorial. Indeed I just tested and the widgets don't work (as imported and used) in jupyter lab. I don't really have time to update to jupyter lab however.
- in jupyter notebook, the code I included does work but of course I don't know if there's an issue with your installation. I would suggest perhaps creating an environment from the environment.yml file included, if you didn't already of course.

> When I run your prefilled file then it will work. Where's the error?
I'm afraid I don't know as you don't post any error message and I cannot replicate your error myself.

**Comment by Niemand112233** [comment]
Hi,
thanks for the fast reply. Do you have any updated repo/tutorial?

I don't get any error message, that's the strange thing. If I use your notebook file it will work. If I copy-paste the lines to a new file it won't work. 

I'm taking the corona-downtime as an opportunity to deepen my programming skills - do you know any other good tutorials?

**Comment by Zabamund** [comment]
Hi, 

so the fact is works in my notebooks but not in a new one suggests your environmnent is ok but perhaps you ran things out of sequence in your notebook? as you're not seeing any error I can't realy help I'm sorry to say.

if the widget is the only thing not working, I'd really recommend their docs, they're really well written and things might have changed since I made this repo.

I'm not planning to update this repo in the near future so I'd say use it with an environment file and make sure you have no typos.

> any other good tutorials

well if you google python tutorial you'll find a plethora of videos and repos out there. If you're looking specifically for geoscience tutorials, I'd suggest [xlines of python](https://github.com/agile-geoscience/xlines) and perhaps visit [swu.ng/slack](swu.ng/slack) for like-minded people.

good luck !
